# fly.toml app configuration file generated for aoma-musixer on 2023-06-22T05:33:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aoma-musixer"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
